### ISSUE TITLE
Get content to float to alternate sides on desktop sizes

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#4]

**Comment by sashaburchuk** [comment]
Having some problems doing this in a way that doesn't make use of parallel containers, because all of our content is different heights. I've tried all of the clear:right clear:left clear:both combos and so far this works the best, but it's still kind of ugly. I am clearfixing the parent container too, just in case you're wondering:

```
article {
  width: 45%;
  &:nth-of-type(odd){
    @media #{$breakpoint} {
    float: left;
    clear: both;
    }
  }
  &:nth-of-type(even){
    @media #{$breakpoint} {
    float: right;
    clear: right;
    }
  }
}
```

I can't really show you what's going on very well in a screenshot but will show you tomorrow!

**Comment by sashaburchuk** [comment]
We are going a different route with how we'll present content.

**Comment by brigleb** [comment]
One thing I would mention here @sashaburchuk : I think we should keep this ticket. We don't need them to float quite the way described, but we *do* need to be able to control when things appear left, right, or center, as we go down the page w/in a year. Should we maybe re-open this?

**Comment by sashaburchuk** [comment]
@brigleb sure thing!
